<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

class Surveys extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        Schema::create('surveys', function (Blueprint $table) {
            $table->id();
            $table->string('name');
            $table->string('email');
            $table->string('phone');
            $table->string('designation')->nullable();
            $table->text('address')->nullable();
            $table->bigInteger('pp_week_25')->default(0);
            $table->bigInteger('pp_week_50')->default(0);
            $table->bigInteger('pp_week_100')->default(0);
            $table->bigInteger('pp_week_250')->default(0);
            $table->bigInteger('pp_week_300')->default(0);
            $table->bigInteger('pp_week_500')->default(0);
            $table->bigInteger('pp_week_750')->default(0);
            $table->bigInteger('pp_week_1000')->default(0);
            $table->bigInteger('pp_week_2500')->default(0);
            $table->bigInteger('pp_week_3200')->default(0);
            $table->bigInteger('pp_week_4500')->default(0);
            $table->bigInteger('pp_month_25')->default(0);
            $table->bigInteger('pp_month_50')->default(0);
            $table->bigInteger('pp_month_100')->default(0);
            $table->bigInteger('pp_month_250')->default(0);
            $table->bigInteger('pp_month_300')->default(0);
            $table->bigInteger('pp_month_500')->default(0);
            $table->bigInteger('pp_month_750')->default(0);
            $table->bigInteger('pp_month_1000')->default(0);
            $table->bigInteger('pp_month_2500')->default(0);
            $table->bigInteger('pp_month_3200')->default(0);
            $table->bigInteger('pp_month_4500')->default(0);
            $table->bigInteger('compartment_week_2cp')->default(0);
            $table->bigInteger('compartment_week_3cp')->default(0);
            $table->bigInteger('compartment_week_4cp')->default(0);
            $table->bigInteger('compartment_week_5cp')->default(0);
            $table->bigInteger('compartment_week_6cp')->default(0);
            $table->bigInteger('compartment_week_8cp')->default(0);
            $table->bigInteger('compartment_month_2cp')->default(0);
            $table->bigInteger('compartment_month_3cp')->default(0);
            $table->bigInteger('compartment_month_4cp')->default(0);
            $table->bigInteger('compartment_month_5cp')->default(0);
            $table->bigInteger('compartment_month_6cp')->default(0);
            $table->bigInteger('compartment_month_8cp')->default(0);
            $table->bigInteger('al_container_with_lid_week_250')->default(0);
            $table->bigInteger('al_container_with_lid_week_450')->default(0);
            $table->bigInteger('al_container_with_lid_week_600')->default(0);
            $table->bigInteger('al_container_with_lid_week_750')->default(0);
            $table->bigInteger('al_container_with_lid_month_250')->default(0);
            $table->bigInteger('al_container_with_lid_month_450')->default(0);
            $table->bigInteger('al_container_with_lid_month_600')->default(0);
            $table->bigInteger('al_container_with_lid_month_750')->default(0);
            $table->bigInteger('p_box_week_idly')->default(0);
            $table->bigInteger('p_box_week_dosa')->default(0);
            $table->bigInteger('p_box_week_sandwich')->default(0);
            $table->bigInteger('p_box_month_idly')->default(0);
            $table->bigInteger('p_box_month_dosa')->default(0);
            $table->bigInteger('p_box_month_sandwich')->default(0);
            $table->bigInteger('p_bag_week_small')->default(0);
            $table->bigInteger('p_bag_week_medium')->default(0);
            $table->bigInteger('p_bag_week_large')->default(0);
            $table->bigInteger('p_bag_week_x_large')->default(0);
            $table->bigInteger('p_bag_month_small')->default(0);
            $table->bigInteger('p_bag_month_medium')->default(0);
            $table->bigInteger('p_bag_month_large')->default(0);
            $table->bigInteger('p_bag_month_x_large')->default(0);
            $table->bigInteger('groccery_bag_week_50')->default(0);
            $table->bigInteger('groccery_bag_week_100')->default(0);
            $table->bigInteger('groccery_bag_week_150')->default(0);
            $table->bigInteger('groccery_bag_week_200')->default(0);
            $table->bigInteger('groccery_bag_week_250')->default(0);
            $table->bigInteger('groccery_bag_week_300')->default(0);
            $table->bigInteger('groccery_bag_week_500')->default(0);
            $table->bigInteger('groccery_bag_week_1')->default(0);
            $table->bigInteger('groccery_bag_week_1_5')->default(0);
            $table->bigInteger('groccery_bag_week_2')->default(0);
            $table->bigInteger('groccery_bag_week_3')->default(0);
            $table->bigInteger('groccery_bag_week_4')->default(0);
            $table->bigInteger('groccery_bag_week_5')->default(0);
            $table->bigInteger('groccery_bag_month_50')->default(0);
            $table->bigInteger('groccery_bag_month_100')->default(0);
            $table->bigInteger('groccery_bag_month_150')->default(0);
            $table->bigInteger('groccery_bag_month_200')->default(0);
            $table->bigInteger('groccery_bag_month_250')->default(0);
            $table->bigInteger('groccery_bag_month_300')->default(0);
            $table->bigInteger('groccery_bag_month_500')->default(0);
            $table->bigInteger('groccery_bag_month_1')->default(0);
            $table->bigInteger('groccery_bag_month_1_5')->default(0);
            $table->bigInteger('groccery_bag_month_2')->default(0);
            $table->bigInteger('groccery_bag_month_3')->default(0);
            $table->bigInteger('groccery_bag_month_4')->default(0);
            $table->bigInteger('groccery_bag_month_5')->default(0);
            $table->bigInteger('garbage_bag_week_small')->default(0);
            $table->bigInteger('garbage_bag_week_medium')->default(0);
            $table->bigInteger('garbage_bag_week_large')->default(0);
            $table->bigInteger('garbage_bag_week_x_large')->default(0);
            $table->bigInteger('garbage_bag_month_small')->default(0);
            $table->bigInteger('garbage_bag_month_medium')->default(0);
            $table->bigInteger('garbage_bag_month_large')->default(0);
            $table->bigInteger('garbage_bag_month_x_large')->default(0);
            $table->bigInteger('tissue_week_22_22')->default(0);
            $table->bigInteger('tissue_week_27_30')->default(0);
            $table->bigInteger('tissue_week_30_30')->default(0);
            $table->bigInteger('tissue_week_32_32')->default(0);
            $table->bigInteger('tissue_week_40_40')->default(0);
            $table->bigInteger('tissue_month_22_22')->default(0);
            $table->bigInteger('tissue_month_27_30')->default(0);
            $table->bigInteger('tissue_month_30_30')->default(0);
            $table->bigInteger('tissue_month_32_32')->default(0);
            $table->bigInteger('tissue_month_40_40')->default(0);
            $table->bigInteger('cuttlery_week_110_spoon')->default(0);
            $table->bigInteger('cuttlery_week_140_spoon')->default(0);
            $table->bigInteger('cuttlery_week_160_spoon')->default(0);
            $table->bigInteger('cuttlery_week_140_fork')->default(0);
            $table->bigInteger('cuttlery_week_160_fork')->default(0);
            $table->bigInteger('cuttlery_month_110_spoon')->default(0);
            $table->bigInteger('cuttlery_month_140_spoon')->default(0);
            $table->bigInteger('cuttlery_month_160_spoon')->default(0);
            $table->bigInteger('cuttlery_month_140_fork')->default(0);
            $table->bigInteger('cuttlery_month_160_fork')->default(0);
            $table->bigInteger('aluminium_week_1kg_gross')->default(0);
            $table->bigInteger('aluminium_week_1kg_net')->default(0);
            $table->bigInteger('aluminium_month_1kg_gross')->default(0);
            $table->bigInteger('aluminium_month_1kg_net')->default(0);
            $table->bigInteger('al_pouch_week_3_5')->default(0);
            $table->bigInteger('al_pouch_week_4_6')->default(0);
            $table->bigInteger('al_pouch_week_5_7')->default(0);
            $table->bigInteger('al_pouch_week_6_8')->default(0);
            $table->bigInteger('al_pouch_week_6_9')->default(0);
            $table->bigInteger('al_pouch_week_7_9')->default(0);
            $table->bigInteger('al_pouch_week_7_10')->default(0);
            $table->bigInteger('al_pouch_week_8_10')->default(0);
            $table->bigInteger('al_pouch_week_9_12')->default(0);
            $table->bigInteger('al_pouch_week_10_12')->default(0);
            $table->bigInteger('al_pouch_week_10_14')->default(0);
            $table->bigInteger('al_pouch_month_3_5')->default(0);
            $table->bigInteger('al_pouch_month_4_6')->default(0);
            $table->bigInteger('al_pouch_month_5_7')->default(0);
            $table->bigInteger('al_pouch_month_6_8')->default(0);
            $table->bigInteger('al_pouch_month_6_9')->default(0);
            $table->bigInteger('al_pouch_month_7_9')->default(0);
            $table->bigInteger('al_pouch_month_7_10')->default(0);
            $table->bigInteger('al_pouch_month_8_10')->default(0);
            $table->bigInteger('al_pouch_month_9_12')->default(0);
            $table->bigInteger('al_pouch_month_10_12')->default(0);
            $table->bigInteger('al_pouch_month_10_14')->default(0);
            $table->bigInteger('billing_roll_week_2')->default(0);
            $table->bigInteger('billing_roll_week_3')->default(0);
            $table->bigInteger('billing_roll_month_2')->default(0);
            $table->bigInteger('billing_roll_month_3')->default(0);
            $table->bigInteger('bopp_tape_week_2')->default(0);
            $table->bigInteger('bopp_tape_week_1')->default(0);
            $table->bigInteger('bopp_tape_month_2')->default(0);
            $table->bigInteger('bopp_tape_month_1')->default(0);
            $table->bigInteger('user_id')->nullable()->references('id')->on('users')->nullOnDelete();
            $table->timestamps();
            $table->softDeletes();
        });
    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        Schema::dropIfExists('surveys');
    }
}
