<?php

namespace App\Exports;

use App\Models\Survey;
use Maatwebsite\Excel\Concerns\FromCollection;
use Maatwebsite\Excel\Concerns\WithHeadings;
use Maatwebsite\Excel\Concerns\WithMapping;
use Illuminate\Support\Facades\Auth;

class SurveyExport implements FromCollection,WithHeadings,WithMapping
{

    /**
    * @return \Illuminate\Support\Collection
    */
    public function headings():array{
        return[
            'id',
            'name',
            'phone',
            'designation',
            'address',
            'pp container 25ml per week',
            'pp container 50ml per week',
            'pp container 100ml per week',
            'pp container 250ml per week',
            'pp container 300ml per week',
            'pp container 500ml per week',
            'pp container 750ml per week',
            'pp container 1000ml per week',
            'pp container 2500ml per week',
            'pp container 3200ml per week',
            'pp container 4500ml per week',
            'pp container 25ml per month',
            'pp container 50ml per month',
            'pp container 100ml per month',
            'pp container 250ml per month',
            'pp container 300ml per month',
            'pp container 500ml per month',
            'pp container 750ml per month',
            'pp container 1000ml per month',
            'pp container 2500ml per month',
            'pp container 3200ml per month',
            'pp container 4500ml per month',
            'pp container 25ml price',
            'pp container 50ml price',
            'pp container 100ml price',
            'pp container 250ml price',
            'pp container 300ml price',
            'pp container 500ml price',
            'pp container 750ml price',
            'pp container 1000ml price',
            'pp container 2500ml price',
            'pp container 3200ml price',
            'pp container 4500ml price',
            'compartment tray 2cp per week',
            'compartment tray 3cp per week',
            'compartment tray 4cp per week',
            'compartment tray 5cp per week',
            'compartment tray 6cp per week',
            'compartment tray 8cp per week',
            'compartment tray 2cp per month',
            'compartment tray 3cp per month',
            'compartment tray 4cp per month',
            'compartment tray 5cp per month',
            'compartment tray 6cp per month',
            'compartment tray 8cp per month',
            'compartment tray 2cp price',
            'compartment tray 3cp price',
            'compartment tray 4cp price',
            'compartment tray 5cp price',
            'compartment tray 6cp price',
            'compartment tray 8cp price',
            'aluminiun container with lid per week 250ml',
            'aluminiun container with lid per week 450ml',
            'aluminiun container with lid per week 600ml',
            'aluminiun container with lid per week 750ml',
            'aluminiun container with lid per month 250ml',
            'aluminiun container with lid per month 450ml',
            'aluminiun container with lid per month 600ml',
            'aluminiun container with lid per month 750ml',
            'aluminiun container with lid price 250ml',
            'aluminiun container with lid price 450ml',
            'aluminiun container with lid price 600ml',
            'aluminiun container with lid price 750ml',
            'paper box per week idly box',
            'paper box per week dosa box',
            'paper box per week sandwich box',
            'paper box per month idly box',
            'paper box per month dosa box',
            'paper box per month sandwich box',
            'paper box price idly box',
            'paper box price dosa box',
            'paper box price sandwich box',
            'paper bag per week small',
            'paper bag per week medium',
            'paper bag per week large',
            'paper bag per week extra large',
            'paper bag per month small',
            'paper bag per month medium',
            'paper bag per month large',
            'paper bag per month extra large',
            'paper bag price small',
            'paper bag price medium',
            'paper bag price large',
            'paper bag price extra large',
            'groccery bag per week 50gms',
            'groccery bag per week 100gms',
            'groccery bag per week 150gms',
            'groccery bag per week 200gms',
            'groccery bag per week 250gms',
            'groccery bag per week 300gms',
            'groccery bag per week 500gms',
            'groccery bag per week 1kg',
            'groccery bag per week 1.5kg',
            'groccery bag per week 2kg',
            'groccery bag per week 3kg',
            'groccery bag per week 4kg',
            'groccery bag per week 5kg',
            'groccery bag per month 50gms',
            'groccery bag per month 100gms',
            'groccery bag per month 150gms',
            'groccery bag per month 200gms',
            'groccery bag per month 250gms',
            'groccery bag per month 300gms',
            'groccery bag per month 500gms',
            'groccery bag per month 1kg',
            'groccery bag per month 1.5kg',
            'groccery bag per month 2kg',
            'groccery bag per month 3kg',
            'groccery bag per month 4kg',
            'groccery bag per month 5kg',
            'groccery bag price 50gms',
            'groccery bag price 100gms',
            'groccery bag price 150gms',
            'groccery bag price 200gms',
            'groccery bag price 250gms',
            'groccery bag price 300gms',
            'groccery bag price 500gms',
            'groccery bag price 1kg',
            'groccery bag price 1.5kg',
            'groccery bag price 2kg',
            'groccery bag price 3kg',
            'groccery bag price 4kg',
            'groccery bag price 5kg',
            'garbage bag per week small',
            'garbage bag per week medium',
            'garbage bag per week large',
            'garbage bag per week x_large',
            'garbage bag per month small',
            'garbage bag per month medium',
            'garbage bag per month large',
            'garbage bag per month x_large',
            'garbage bag price small',
            'garbage bag price medium',
            'garbage bag price large',
            'garbage bag price x_large',
            'tissues per week 22*22',
            'tissues per week 27*30',
            'tissues per week 30*30',
            'tissues per week 32*32',
            'tissues per week 40*40',
            'tissues per month 22*22',
            'tissues per month 27*30',
            'tissues per month 30*30',
            'tissues per month 32*32',
            'tissues per month 40*40',
            'tissues price 22*22',
            'tissues price 27*30',
            'tissues price 30*30',
            'tissues price 32*32',
            'tissues price 40*40',
            'cutlery per week 110mm spoon',
            'cutlery per week 140mm spoon',
            'cutlery per week 160mm spoon',
            'cutlery per week 140mm fork',
            'cutlery per week 160mm fork',
            'cuttlery per month 110mm spoon',
            'cuttlery per month 140mm spoon',
            'cuttlery per month 160mm spoon',
            'cuttlery per month 140mm fork',
            'cuttlery per month 160mm fork',
            'cutlery price 110mm spoon',
            'cutlery price 140mm spoon',
            'cutlery price 160mm spoon',
            'cutlery price 140mm fork',
            'cutlery price 160mm fork',
            'aluminium foil per week 1kg gross',
            'aluminium foil per week 1kg net',
            'aluminium foil per month 1kg gross',
            'aluminium foil per month 1kg net',
            'aluminium foil price 1kg gross',
            'aluminium foil price 1kg net',
            '6 layer aluminium coated pouch per week 3x5',
            '6 layer aluminium coated pouch per week 4x6',
            '6 layer aluminium coated pouch per week 5x7',
            '6 layer aluminium coated pouch per week 6x8',
            '6 layer aluminium coated pouch per week 6x9',
            '6 layer aluminium coated pouch per week 7x9',
            '6 layer aluminium coated pouch per week 7x10',
            '6 layer aluminium coated pouch per week 8x10',
            '6 layer aluminium coated pouch per week 9x12',
            '6 layer aluminium coated pouch per week 10x12',
            '6 layer aluminium coated pouch per week 10x14',
            '6 layer aluminium coated pouch per month 3x5',
            '6 layer aluminium coated pouch per month 4x6',
            '6 layer aluminium coated pouch per month 5x7',
            '6 layer aluminium coated pouch per month 6x8',
            '6 layer aluminium coated pouch per month 6x9',
            '6 layer aluminium coated pouch per month 7x9',
            '6 layer aluminium coated pouch per month 7x10',
            '6 layer aluminium coated pouch per month 8x10',
            '6 layer aluminium coated pouch per month 9x12',
            '6 layer aluminium coated pouch per month 10x12',
            '6 layer aluminium coated pouch per month 10x14',
            '6 layer aluminium coated pouch price 3x5',
            '6 layer aluminium coated pouch price 4x6',
            '6 layer aluminium coated pouch price 5x7',
            '6 layer aluminium coated pouch price 6x8',
            '6 layer aluminium coated pouch price 6x9',
            '6 layer aluminium coated pouch price 7x9',
            '6 layer aluminium coated pouch price 7x10',
            '6 layer aluminium coated pouch price 8x10',
            '6 layer aluminium coated pouch price 9x12',
            '6 layer aluminium coated pouch price 10x12',
            '6 layer aluminium coated pouch price 10x14',
            'bopp tape per week 1"',
            'bopp tape per week 2"',
            'bopp tape per month 1"',
            'bopp tape per month 2"',
            'bopp tape price 1"',
            'bopp tape price 2"',
            'billing roll per week 3"',
            'billing roll per week 2"',
            'billing roll per month 3"',
            'billing roll per month 2"',
            'billing roll price 3"',
            'billing roll price 2"',
            'Advance payment to be done within',
            'Advance payment to be done in cash',
            'staff',
            'created_at',
        ];
    }
    public function map($data): array
    {
         return[
            $data->id,
            $data->name,
            $data->phone,
            $data->designation,
            $data->address,
            $data->pp_week_25,
            $data->pp_week_50,
            $data->pp_week_100,
            $data->pp_week_250,
            $data->pp_week_300,
            $data->pp_week_500,
            $data->pp_week_750,
            $data->pp_week_1000,
            $data->pp_week_2500,
            $data->pp_week_3200,
            $data->pp_week_4500,
            $data->pp_month_25,
            $data->pp_month_50,
            $data->pp_month_100,
            $data->pp_month_250,
            $data->pp_month_300,
            $data->pp_month_500,
            $data->pp_month_750,
            $data->pp_month_1000,
            $data->pp_month_2500,
            $data->pp_month_3200,
            $data->pp_month_4500,
            $data->pp_price_25,
            $data->pp_price_50,
            $data->pp_price_100,
            $data->pp_price_250,
            $data->pp_price_300,
            $data->pp_price_500,
            $data->pp_price_750,
            $data->pp_price_1000,
            $data->pp_price_2500,
            $data->pp_price_3200,
            $data->pp_price_4500,
            $data->compartment_week_2cp,
            $data->compartment_week_3cp,
            $data->compartment_week_4cp,
            $data->compartment_week_5cp,
            $data->compartment_week_6cp,
            $data->compartment_week_8cp,
            $data->compartment_month_2cp,
            $data->compartment_month_3cp,
            $data->compartment_month_4cp,
            $data->compartment_month_5cp,
            $data->compartment_month_6cp,
            $data->compartment_month_8cp,
            $data->compartment_price_2cp,
            $data->compartment_price_3cp,
            $data->compartment_price_4cp,
            $data->compartment_price_5cp,
            $data->compartment_price_6cp,
            $data->compartment_price_8cp,
            $data->al_container_with_lid_week_250,
            $data->al_container_with_lid_week_450,
            $data->al_container_with_lid_week_600,
            $data->al_container_with_lid_week_750,
            $data->al_container_with_lid_month_250,
            $data->al_container_with_lid_month_450,
            $data->al_container_with_lid_month_600,
            $data->al_container_with_lid_month_750,
            $data->al_container_with_lid_price_250,
            $data->al_container_with_lid_price_450,
            $data->al_container_with_lid_price_600,
            $data->al_container_with_lid_price_750,
            $data->p_box_week_idly,
            $data->p_box_week_dosa,
            $data->p_box_week_sandwich,
            $data->p_box_month_idly,
            $data->p_box_month_dosa,
            $data->p_box_month_sandwich,
            $data->p_box_price_idly,
            $data->p_box_price_dosa,
            $data->p_box_price_sandwich,
            $data->p_bag_week_small,
            $data->p_bag_week_medium,
            $data->p_bag_week_large,
            $data->p_bag_week_x_large,
            $data->p_bag_month_small,
            $data->p_bag_month_medium,
            $data->p_bag_month_large,
            $data->p_bag_month_x_large,
            $data->p_bag_price_small,
            $data->p_bag_price_medium,
            $data->p_bag_price_large,
            $data->p_bag_price_x_large,
            $data->groccery_bag_week_50,
            $data->groccery_bag_week_100,
            $data->groccery_bag_week_150,
            $data->groccery_bag_week_200,
            $data->groccery_bag_week_250,
            $data->groccery_bag_week_300,
            $data->groccery_bag_week_500,
            $data->groccery_bag_week_1,
            $data->groccery_bag_week_1_5,
            $data->groccery_bag_week_2,
            $data->groccery_bag_week_3,
            $data->groccery_bag_week_4,
            $data->groccery_bag_week_5,
            $data->groccery_bag_month_50,
            $data->groccery_bag_month_100,
            $data->groccery_bag_month_150,
            $data->groccery_bag_month_200,
            $data->groccery_bag_month_250,
            $data->groccery_bag_month_300,
            $data->groccery_bag_month_500,
            $data->groccery_bag_month_1,
            $data->groccery_bag_month_1_5,
            $data->groccery_bag_month_2,
            $data->groccery_bag_month_3,
            $data->groccery_bag_month_4,
            $data->groccery_bag_month_5,
            $data->groccery_bag_price_50,
            $data->groccery_bag_price_100,
            $data->groccery_bag_price_150,
            $data->groccery_bag_price_200,
            $data->groccery_bag_price_250,
            $data->groccery_bag_price_300,
            $data->groccery_bag_price_500,
            $data->groccery_bag_price_1,
            $data->groccery_bag_price_1_5,
            $data->groccery_bag_price_2,
            $data->groccery_bag_price_3,
            $data->groccery_bag_price_4,
            $data->groccery_bag_price_5,
            $data->garbage_bag_week_small,
            $data->garbage_bag_week_medium,
            $data->garbage_bag_week_large,
            $data->garbage_bag_week_x_large,
            $data->garbage_bag_month_small,
            $data->garbage_bag_month_medium,
            $data->garbage_bag_month_large,
            $data->garbage_bag_month_x_large,
            $data->garbage_bag_price_small,
            $data->garbage_bag_price_medium,
            $data->garbage_bag_price_large,
            $data->garbage_bag_price_x_large,
            $data->tissue_week_22_22,
            $data->tissue_week_27_30,
            $data->tissue_week_30_30,
            $data->tissue_week_32_32,
            $data->tissue_week_40_40,
            $data->tissue_month_22_22,
            $data->tissue_month_27_30,
            $data->tissue_month_30_30,
            $data->tissue_month_32_32,
            $data->tissue_month_40_40,
            $data->tissue_price_22_22,
            $data->tissue_price_27_30,
            $data->tissue_price_30_30,
            $data->tissue_price_32_32,
            $data->tissue_price_40_40,
            $data->cuttlery_week_110_spoon,
            $data->cuttlery_week_140_spoon,
            $data->cuttlery_week_160_spoon,
            $data->cuttlery_week_140_fork,
            $data->cuttlery_week_160_fork,
            $data->cuttlery_month_110_spoon,
            $data->cuttlery_month_140_spoon,
            $data->cuttlery_month_160_spoon,
            $data->cuttlery_month_140_fork,
            $data->cuttlery_month_160_fork,
            $data->cuttlery_price_110_spoon,
            $data->cuttlery_price_140_spoon,
            $data->cuttlery_price_160_spoon,
            $data->cuttlery_price_140_fork,
            $data->cuttlery_price_160_fork,
            $data->aluminium_week_1kg_gross,
            $data->aluminium_month_1kg_gross,
            $data->aluminium_price_1kg_gross,
            $data->aluminium_price_1kg_net,
            $data->al_pouch_week_3_5,
            $data->al_pouch_week_4_6,
            $data->al_pouch_week_5_7,
            $data->al_pouch_week_6_8,
            $data->al_pouch_week_6_9,
            $data->al_pouch_week_7_9,
            $data->al_pouch_week_7_10,
            $data->al_pouch_week_8_10,
            $data->al_pouch_week_9_12,
            $data->al_pouch_week_10_12,
            $data->al_pouch_week_10_14,
            $data->al_pouch_month_3_5,
            $data->al_pouch_month_4_6,
            $data->al_pouch_month_5_7,
            $data->al_pouch_month_6_8,
            $data->al_pouch_month_6_9,
            $data->al_pouch_month_7_9,
            $data->al_pouch_month_7_10,
            $data->al_pouch_month_8_10,
            $data->al_pouch_month_9_12,
            $data->al_pouch_month_10_12,
            $data->al_pouch_month_10_14,
            $data->al_pouch_price_3_5,
            $data->al_pouch_price_4_6,
            $data->al_pouch_price_5_7,
            $data->al_pouch_price_6_8,
            $data->al_pouch_price_6_9,
            $data->al_pouch_price_7_9,
            $data->al_pouch_price_7_10,
            $data->al_pouch_price_8_10,
            $data->al_pouch_price_9_12,
            $data->al_pouch_price_10_12,
            $data->al_pouch_price_10_14,
            $data->bopp_tape_week_1,
            $data->bopp_tape_week_2,
            $data->bopp_tape_month_1,
            $data->bopp_tape_month_2,
            $data->bopp_tape_price_1,
            $data->bopp_tape_price_2,
            $data->billing_roll_week_3,
            $data->billing_roll_week_2,
            $data->billing_roll_month_3,
            $data->billing_roll_month_2,
            $data->billing_roll_price_3,
            $data->billing_roll_price_2,
            $data->payment_duration,
            $data->cash_payment,
            $data->staff->name,
            $data->created_at,
         ];
    }
    public function collection()
    {
        $data = Survey::with('Staff');
        if(Auth::check() && Auth::user()->userType==2){
            $data->where('user_id', Auth::id());
        }
        $data = $data->get();
        return $data;
    }
}
